### ISSUE TITLE
Migrate globalbrainconsortium.org to point to this repo

### ISSUE THREAD

**Issue by 3design** [aces/gbc_website#18]
Change globalbrainconsortium.org url to point to this repo.

We took the following steps:

- changed A records as per instructions [here ](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site)
- edit packages.json line 11 and removed the prefix
-- [commit](https://github.com/aces/gbc_website/commit/137c5a4fe47f91211c284132e7da34d4b12002c5)
- create a CNAME file in root/src so that when the site rebuilds, it includes the CNAME file on gh-pages branch
-- [commit](https://github.com/aces/gbc_website/commit/8ceee5029175e0fac69c6f4b49c1cb08c953e456)

**Comment by christinerogers** [comment]
thanks @3design  -- please edit your description above to link to the commits you mention, and then please close this as completed. (given it's testd and working to your satisfaction)

**Comment by 3design** [comment]
added links to the commits referenced above. Closing issue
