### ISSUE TITLE
change A references for globalbrainconsortium.org

### ISSUE THREAD

**Issue by selineriz** [aces/gbc_website#19]
@christinerogers:
Currently, the url is masking and this causes the site to not show the page names in the url bar. We need to edit this after the event is over. Refer to [this link](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain) for instruction on how to set this up

Old repo link: https://github.com/3design/gbc/issues/34

**Comment by 3design** [comment]
This has been addressed in [issue 18](https://github.com/aces/gbc_website/issues/18) and can be closed

**Comment by christinerogers** [comment]
closing per Derek's comment that this is done
