### ISSUE TITLE
bring updates to 2024 event page from old repo

### ISSUE THREAD

**Issue by 3design** [aces/gbc_website#2]
- [x] copy page from old repo to this repo

**Comment by 3design** [comment]
Changes merged and are visible on https://aces.github.io/gbc_website/event-annualMeeting-sept2024/

**Comment by christinerogers** [comment]
this brings selin's latest updates post-gbc meeting, yes?  

Just noticed the website visitors are still being asked on the page to register for this Past event which doesn't make sense -- just opened a [new issue](https://github.com/aces/gbc_website/issues/9) for @selineriz to follow up with a new PR.
