### ISSUE TITLE
Custom domain name and CNAME file causes a redirect

### ISSUE THREAD

**Issue by selineriz** [aces/gbc_website#20]
@3design:
I had added a CNAME file to the /src folder, and decided to remove it after it continued to redirect to the globalbrainconsortium.org url (not what I wanted to do). The CNAME file also seemed to change the Custom Domain Name in the settings. I removed that entry and the site showed correctly.

After this, every code push to github, the site would redirect to globalbrainconsortium.org and the Custom Domain Name field would be auto-filled. I would remove it to fix the redirect, but upon pushing more code, it would redirect again.

I found a CNAME file in /dist and removed it as well as cleared the Custom Domain Name in the settings. This seems to have fixed the issue. I have tested some code pushes and so far, so good. I will keep this issue open in the event that it happens again.

Old repo link: https://github.com/3design/gbc/issues/32

**Comment by 3design** [comment]
This issue has been addressed and is no longer needed. I believe this issue is safe to close.

**Comment by christinerogers** [comment]
Thanks Derek, agreed this was resolved by [this commit of yours last week]( https://github.com/aces/gbc_website/commit/8ceee5029175e0fac69c6f4b49c1cb08c953e456#diff-a5206d547f902c80fa9d5a011d31a293109674e55c095c9fcebcff28d6bc2294)
I'm linking that commit here so this is nicely organized, and closing.
