### ISSUE TITLE
Review GBC website and codebase for traces of old Immersive project.

### ISSUE THREAD

**Issue by christinerogers** [aces/gbc_website#23]
Spinoff from #6 -- 
@selineriz could please re-read over the website and do a few quick searches on this repo codebase to confirm / check that the below looks resolved to you?   
If you don't find anything please leave a comment and tag this as `cleanup`.  

For Context: this site is an adaptation of the Immersive  Healthcare project Website here: https://immersivehealthcare.org/
whose codebase we copied from colleagues here -- https://github.com/vr-leeds/ihc-website-development
The idea is to check that we completely replaced/updated anywhere it might still indicate the Immersive project to users / visitors, even in the codebase. 
(There will be a few exceptional cases where we may keep examples of old or hidden/unused features from the Immersive site, just to have on hand for reference in this repo). 

So if/when you find these traces, please triage (order by what seems most important) and document here, thanks -- 

> This was done as a first pass in august but I think it's worth a second look now. 
> 
> Closing this and spinning off the followup into another issue for @selineriz 
>  

 _Originally posted by @christinerogers in [#6](https://github.com/aces/gbc_website/issues/6#issuecomment-2429762024)_

**Comment by selineriz** [comment]
Both the website and repo codebase look good @christinerogers

**Comment by christinerogers** [comment]
thanks @selineriz - closing this
