### ISSUE TITLE
Update text on Contact Page

### ISSUE THREAD

**Issue by selineriz** [aces/gbc_website#4]
**@3design:**
- [ ]  Contact page text taken from GBC website. This can be updated as needed

Contact the Global Brain Consortium
There are several ways to get involved in the GBC:

Share your unique perspectives, experiences, and knowledge with members around the world to create solutions that positively impact global mental health.
Enhance your expertise by networking with leading professionals, discovering the latest trends in brain imaging, leveraging your scientific research, and being part of a global brain network.
Become a member of one of our working groups or create your own special interest group.

**@christinerogers:** 
agreed this does not look amazing but the text is fine for now.

the way it's displayed however violates the alan rule of blank space at the end of wrapped lines

Please have a go at making it look better on the page - could a narrower frame constraining its width?
would spacing between the paragraphs make them look less like run-on sentences ?

**@3design:**
I've added some margin below the link items so that they are not too close together. If that doesn't suite your needs, we can add the boxes as seen on https://3design.github.io/gbc/about/

Old repo link (3design/gbc): https://github.com/3design/gbc/issues/10

**Comment by christinerogers** [comment]
@3design i think it's ok with the current updates and without the grey background boxes for now.  resolving for now.
