### ISSUE TITLE
update the readme

### ISSUE THREAD

**Issue by selineriz** [aces/gbc_website#6]
@christinerogers: 
Please rename and/or remove what clearly belongs to the Immersive project and isn't reelvant to this repo.
Most of the technical instructions can stay, given they're reasonably updated/accurate for our case.

please also search the repo for anywhere else Immersive.. or the ihg acronym (or any terms like that) are still in the repo -- it's time to replace them, particularly before we invite people to test-contribute

-@3design  added a commit that referenced this issue [on Aug 28](https://github.com/3design/gbc/issues/16#ref-commit-84b824a)- 

Old repo link (3design/gbc): https://github.com/3design/gbc/issues/16

**Comment by christinerogers** [comment]
This was done as a first pass in august but I think it's worth a second look now. 

Closing this and spinning off the followup into another issue for @selineriz
