### ISSUE TITLE
GBC Sept meeting: remove registration info for Past events

### ISSUE THREAD

**Issue by christinerogers** [aces/gbc_website#9]
Hi Selin there is a major update left to do on this page -- missed in the [first PR](https://github.com/aces/gbc_website/pull/3)
Please remove the button, qr code and text requesting people to register for a past event on : 
https://aces.github.io/gbc_website/event-annualMeeting-sept2024/

Note The blue button to `Register...` should also be removed -- try identifying and deleting this (it should work fairly simply)

**Comment by selineriz** [comment]
#11

**Comment by 3design** [comment]
PR merged and site has updated https://aces.github.io/gbc_website/event-annualMeeting-sept2024/

**Comment by christinerogers** [comment]
Congrats @selineriz on your first PR merged 🎉
